project_id = "kpswxkuzfnafsqeqaunt"

[functions.notify-events]
verify_jwt = false

[functions.get-users]
verify_jwt = true

[functions.notify-new-user]
verify_jwt = false

[functions.notify-comment]
verify_jwt = false
