project_id = "kpswxkuzfnafsqeqaunt"

[functions.notify-events]
verify_jwt = false

[functions.get-users]
verify_jwt = true

[functions.notify-new-user]
verify_jwt = false

[functions.notify-comment]
verify_jwt = false

[functions.auto-publish]
verify_jwt = false

[functions.translate-post]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.send-segmented-email]
verify_jwt = false

[functions.og-image]
verify_jwt = false

[functions.track-email]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.push-subscribe]
verify_jwt = false

[functions.send-push]
verify_jwt = false
